services:
  voidscreenshare:
    image: voidscreenshare
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
